### ISSUE TITLE
how to share dependencies?

### ISSUE THREAD

**Issue by ersel** [theburningmonk/lambda-monorepo-code-sharing-demo#1]
Hi Yan, Hope all is well! Thanks for sharing this example.

I am wondering how can you share dependencies (node_modules) between services?

Let's assume library file `libraries/library-a/index.js` made use of `lodash` or some other package. Then services which rely on it would need to install this package as well...

I am currently building an Express API which has lots of utilities, but would like to experiment along with some lambda tasks within a monorepo setting. 

Would Yarn workspaces work for us? I've also come across this package but can't tell if it will solve the problem... 

https://github.com/Butterwire/serverless-plugin-monorepo

Do you have any suggestions how to go about this?

**Comment by pepoviola** [comment]
Hi @ersel, don't know if you already resolve this issue. But, in a similar case I use a layer for sharing all the deps but require an extra step for build/deploy. Ping me if you still need help.

**Comment by ersel** [comment]
Thanks @pepoviola I solved the issue by some CI/CD automation! layers is a good shout as well
